### ISSUE TITLE
Motor get bricked after using Motor.on() with very high value for speed

### ISSUE THREAD

**Issue by tibaultbordeaux** [RaspberryPiFoundation/picozero#115]
**Is your feature request related to a problem? Please describe.**
One of my students ended up with a bricked motor, after using the method "Motor" from the picozero library. He entered a very high value for the speed parameter, i.a. speed=1000. After that the motor was getting hot and stopped working.

**Describe the solution you'd like**
The function Motor.on should automatically lower all values higher than 1 to 1.

**Describe alternatives you've considered**
The function Motor.on could not allow higher values than 1 for the speed value.

**Comment by martinohanlon** [comment]
A value of 1 or greater than will result in the PWM pin being 'on' all the time (i.e. when set to 0.5 the pin is on half the time). 

There would be no difference in output on the pwm pin whether the value was 1 or 1000.

There is no validation on the pin values because outside the bounds it has no effect and adds complexity.

**Comment by tibaultbordeaux** [comment]
Ok, thanks for the explanation. 
Must be another fault with the engine.

Entry can be deleted.

Thank you for your great library!
I use it very extensively!
